//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.07 at 08:52:12 PM CET 
//


package goetzmaster;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}systemInfo"/>
 *         &lt;element ref="{}cpu"/>
 *         &lt;element ref="{}graphics_card"/>
 *         &lt;element ref="{}audio_card"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "systemInfo",
    "graphicsCard"
    
})
@XmlRootElement(name = "hardware_settings_info")
public class HardwareSettingsInfo {

    @XmlElement(required = true)
    protected SystemInfo systemInfo;
   

    @XmlElement(name = "graphics_card", required = true)
    protected GraphicsCard graphicsCard;
    
   
    /**
     * Gets the value of the systemInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SystemInfo }
     *     
     */
    public SystemInfo getSystemInfo() {
        return systemInfo;
    }

    /**
     * Sets the value of the systemInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemInfo }
     *     
     */
    public void setSystemInfo(SystemInfo value) {
        this.systemInfo = value;
    }

    /**
     * Gets the value of the cpu property.
     * 
     * @return
     *     possible object is
     *     {@link Cpu }
     *     
     */
   

    /**
     * Sets the value of the cpu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cpu }
     *     
     */
    

    /**
     * Gets the value of the graphicsCard property.
     * 
     * @return
     *     possible object is
     *     {@link GraphicsCard }
     *     
     */
    public GraphicsCard getGraphicsCard() {
        return graphicsCard;
    }

    /**
     * Sets the value of the graphicsCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link GraphicsCard }
     *     
     */
    public void setGraphicsCard(GraphicsCard value) {
        this.graphicsCard = value;
    }

    /**
     * Gets the value of the audioCard property.
     * 
     * @return
     *     possible object is
     *     {@link AudioCard }
     *     
     */
    

    /**
     * Sets the value of the audioCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioCard }
     *     
     */
  

}
